pool:
  name: Azure Pipelines
steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Azure Deployment:Create Azure Container Registry'
  inputs:
    azureSubscription: 'Visual Studio Enterprise (a535e62b-a7ce-4066-a004-6d4308347264)'
    resourceGroupName: 'yiliueshoponcontainers-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Microsoft/devops-project-samples/057f6cc268a62922d012067d069d58684e967d0a/armtemplates/kubernetes/containerRegistry-template.json'
    overrideParameters: '-registryName "yiliueshoponcontainersacr" -registryLocation "South Central US" -registrySku "Standard"'

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: 'Visual Studio Enterprise (a535e62b-a7ce-4066-a004-6d4308347264)'
    azureContainerRegistry: yiliueshoponcontainersacr.azurecr.io
    imageName: 'yiliueshoponcontainersacr.azurecr.io/yiliueshoponcontainers:$(Build.BuildId)'

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'Visual Studio Enterprise (a535e62b-a7ce-4066-a004-6d4308347264)'
    azureContainerRegistry: yiliueshoponcontainersacr.azurecr.io
    command: 'Push an image'
    imageName: 'yiliueshoponcontainersacr.azurecr.io/yiliueshoponcontainers:$(Build.BuildId)'

- task: HelmInstaller@0
  displayName: 'Install Helm 3.*.*'
  inputs:
    helmVersion: 3.0.2
    checkLatestHelmVersion: false
    kubectlVersion: 1.10.3
    checkLatestKubectl: false

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    azureSubscription: 'yiliueshoponcontainers - Azure'
    azureResourceGroup: 'yiliueshoponcontainers-rg'
    kubernetesCluster: yiliueshoponcontainers
    command: package
    chartPath: deploy/k8s/helm
    save: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
